---
- hosts: all
  become: yes 
  tasks:
    - name: "Clean machine"
      include_role:
        name: cleaner

- hosts: brokers
  become: yes 
  tasks:
    - name: "Install Kafka"
      include_role:
        name: kafka
        tasks_from: install
