- name: Stop Services
  become: yes
  systemd:
    name: '{{item}}'
    state: stopped
  with_items:
    - "kafka"
    - "zookeeper"
  register: stop_service
  failed_when:
    - stop_service.failed == true
    - '"Could not find the requested service" not in stop_service.msg'

- name: Remove kafka and zookeeper
  become: yes
  apt:
    name: '{{item}}'
    state: absent
    update_cache: yes
  with_items:
    - "kafka"
    - "zookeeper"
  register: remove_service
  failed_when:
    - remove_service.failed == true
    - '"Could not find the requested service" not in remove_service.msg'

- name: Remove JRE 
  become: yes
  apt:
    name: 
      - default-jre
    state: absent
    update_cache: yes

- name: Delete an user 
  become: yes
  user:
    name: kafka
    state: absent
    group: kafka

- name: Delete a group 
  become: yes
  group:
    name: kafka
    state: absent



- shell: ls -1 {{installation_dir}}
  register: contents
- file: 
    path: "{{installation_dir}}/{{ item }}"
    state: absent
    with_items: {{ contents.stdout_lines }}
    
- name: Remove config files
  become: yes
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/etc/systemd/system/kafka.service"
    - "/etc/systemd/system/zookeeper.service"